<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DevilDaggersInfo.Web.Core.Utils\DevilDaggersInfo.Web.Core.Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <GlobalAnalyzerConfigFiles Include="..\Tests.globalconfig" />
  </ItemGroup>

</Project>
