using DevilDaggersInfo.Api.Ddcl.CustomLeaderboards;
using DevilDaggersInfo.Web.Server.Domain.Models.CustomLeaderboards;

namespace DevilDaggersInfo.Web.Server.Converters.ApiToDomain.Ddcl;

public static class CustomLeaderboardConverters
{
	public static UploadRequest ToDomain(this AddUploadRequest uploadRequest) => new(
		survivalHashMd5: uploadRequest.SurvivalHashMd5,
		playerId: uploadRequest.PlayerId,
		playerName: uploadRequest.PlayerName,
		replayPlayerId: uploadRequest.ReplayPlayerId,
		timeInSeconds: uploadRequest.TimeInSeconds,
		timeAsBytes: uploadRequest.TimeAsBytes,
		gemsCollected: uploadRequest.GemsCollected,
		enemiesKilled: uploadRequest.EnemiesKilled,
		daggersFired: uploadRequest.DaggersFired,
		daggersHit: uploadRequest.DaggersHit,
		enemiesAlive: uploadRequest.EnemiesAlive,
		homingStored: uploadRequest.HomingStored,
		homingEaten: uploadRequest.HomingEaten,
		gemsDespawned: uploadRequest.GemsDespawned,
		gemsEaten: uploadRequest.GemsEaten,
		gemsTotal: uploadRequest.GemsTotal,
		deathType: uploadRequest.DeathType,
		levelUpTime2InSeconds: uploadRequest.LevelUpTime2InSeconds,
		levelUpTime3InSeconds: uploadRequest.LevelUpTime3InSeconds,
		levelUpTime4InSeconds: uploadRequest.LevelUpTime4InSeconds,
		levelUpTime2AsBytes: uploadRequest.LevelUpTime2AsBytes,
		levelUpTime3AsBytes: uploadRequest.LevelUpTime3AsBytes,
		levelUpTime4AsBytes: uploadRequest.LevelUpTime4AsBytes,
		clientVersion: uploadRequest.ClientVersion,
		client: uploadRequest.Client,
		operatingSystem: uploadRequest.OperatingSystem,
		buildMode: uploadRequest.BuildMode,
		validation: uploadRequest.Validation,
		validationVersion: uploadRequest.ValidationVersion,
		isReplay: uploadRequest.IsReplay,
		prohibitedMods: uploadRequest.ProhibitedMods,
		gameMode: uploadRequest.GameMode,
		timeAttackOrRaceFinished: uploadRequest.TimeAttackOrRaceFinished,
		gameData: new UploadRequestData
		{
			GemsCollected = uploadRequest.GameData.GemsCollected,
			EnemiesKilled = uploadRequest.GameData.EnemiesKilled,
			DaggersFired = uploadRequest.GameData.DaggersFired,
			DaggersHit = uploadRequest.GameData.DaggersHit,
			EnemiesAlive = uploadRequest.GameData.EnemiesAlive,
			HomingStored = uploadRequest.GameData.HomingStored,
			HomingEaten = uploadRequest.GameData.HomingEaten,
			GemsDespawned = uploadRequest.GameData.GemsDespawned,
			GemsEaten = uploadRequest.GameData.GemsEaten,
			GemsTotal = uploadRequest.GameData.GemsTotal,
			Skull1sAlive = uploadRequest.GameData.Skull1sAlive,
			Skull2sAlive = uploadRequest.GameData.Skull2sAlive,
			Skull3sAlive = uploadRequest.GameData.Skull3sAlive,
			SpiderlingsAlive = uploadRequest.GameData.SpiderlingsAlive,
			Skull4sAlive = uploadRequest.GameData.Skull4sAlive,
			Squid1sAlive = uploadRequest.GameData.Squid1sAlive,
			Squid2sAlive = uploadRequest.GameData.Squid2sAlive,
			Squid3sAlive = uploadRequest.GameData.Squid3sAlive,
			CentipedesAlive = uploadRequest.GameData.CentipedesAlive,
			GigapedesAlive = uploadRequest.GameData.GigapedesAlive,
			Spider1sAlive = uploadRequest.GameData.Spider1sAlive,
			Spider2sAlive = uploadRequest.GameData.Spider2sAlive,
			LeviathansAlive = uploadRequest.GameData.LeviathansAlive,
			OrbsAlive = uploadRequest.GameData.OrbsAlive,
			ThornsAlive = uploadRequest.GameData.ThornsAlive,
			GhostpedesAlive = uploadRequest.GameData.GhostpedesAlive,
			SpiderEggsAlive = uploadRequest.GameData.SpiderEggsAlive,
			Skull1sKilled = uploadRequest.GameData.Skull1sKilled,
			Skull2sKilled = uploadRequest.GameData.Skull2sKilled,
			Skull3sKilled = uploadRequest.GameData.Skull3sKilled,
			SpiderlingsKilled = uploadRequest.GameData.SpiderlingsKilled,
			Skull4sKilled = uploadRequest.GameData.Skull4sKilled,
			Squid1sKilled = uploadRequest.GameData.Squid1sKilled,
			Squid2sKilled = uploadRequest.GameData.Squid2sKilled,
			Squid3sKilled = uploadRequest.GameData.Squid3sKilled,
			CentipedesKilled = uploadRequest.GameData.CentipedesKilled,
			GigapedesKilled = uploadRequest.GameData.GigapedesKilled,
			Spider1sKilled = uploadRequest.GameData.Spider1sKilled,
			Spider2sKilled = uploadRequest.GameData.Spider2sKilled,
			LeviathansKilled = uploadRequest.GameData.LeviathansKilled,
			OrbsKilled = uploadRequest.GameData.OrbsKilled,
			ThornsKilled = uploadRequest.GameData.ThornsKilled,
			GhostpedesKilled = uploadRequest.GameData.GhostpedesKilled,
			SpiderEggsKilled = uploadRequest.GameData.SpiderEggsKilled,
		},
		replayData: uploadRequest.ReplayData,
		status: uploadRequest.Status);
}
