using System.Text;

namespace DevilDaggersInfo.Tool.GenerateClient.Extensions;

public static class StringExtensions
{
	private const string _fileHeader = """
		// <auto-generated>
		// This code was generated by DevilDaggersInfo.
		// </auto-generated>
		""";

	private static readonly string[] _suppressionCodes =
	{
		"CS0105",
		"CS1591",
		"CS8618",
		"RCS1214",
		"S1128",
		"SA1001",
		"SA1027",
		"SA1028",
		"SA1101",
		"SA1122",
		"SA1137",
		"SA1200",
		"SA1201",
		"SA1208",
		"SA1210",
		"SA1309",
		"SA1311",
		"SA1413",
		"SA1503",
		"SA1505",
		"SA1507",
		"SA1508",
		"SA1516",
		"SA1600",
		"SA1601",
		"SA1602",
		"SA1623",
		"SA1649",
	};

	private static readonly string _warningSuppressionCodes = string.Join(", ", _suppressionCodes);

	public static string BuildSource(this string code, string newLine = "\n")
	{
		StringBuilder stringBuilder = new(_fileHeader);
		stringBuilder
			.Append(newLine)
			.Append(newLine)
			.Append("#pragma warning disable ")
			.Append(_warningSuppressionCodes)
			.Append(newLine)
			.Append(newLine)
			.Append("#nullable enable")
			.Append(newLine)
			.Append(newLine)
			.Append(code);

		return stringBuilder.ToString().TrimCode();
	}

	private static string TrimCode(this string code, string newLine = "\n")
	{
		StringBuilder stringBuilder = new();
		foreach (string line in code.Split(new[] { newLine }, StringSplitOptions.None))
			stringBuilder.AppendLine(line.TrimEnd());

		return stringBuilder.ToString();
	}

	public static string IndentCode(this string code, int count, string newLine = "\n")
	{
		string indentation = new('\t', count);
		return code.Insert(0, indentation).Replace(newLine, newLine + indentation);
	}

	public static string TrimStart(this string str, params string[] values)
	{
		if (values.Length == 0)
			return str;

		string? sub = Array.Find(values, str.StartsWith);
		return sub == null ? str : str[sub.Length..];
	}

	public static string ToUsingDirective(this string namespaceString)
		=> $"using {namespaceString};";

	public static string[] ExtractLines(this string str)
		=> str.Split(new[] { '\n' }, StringSplitOptions.RemoveEmptyEntries).Select(s => s.Trim()).ToArray();
}
