global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Numerics;
global using Warp.NET;
global using Warp.NET.Numerics;
global using static Warp.NET.Graphics;
global using Shader = Warp.NET.Content.Shader;
global using Texture = Warp.NET.Content.Texture;
global using WarpCharsets = DevilDaggersInfo.App.Ui.Base.Charsets;
global using WarpModels = DevilDaggersInfo.App.Ui.Base.Models;
global using WarpShaders = DevilDaggersInfo.App.Ui.Base.Shaders;
global using WarpShaderUniformInitializer = DevilDaggersInfo.App.Ui.Base.ShaderUniformInitializer;
global using WarpSounds = DevilDaggersInfo.App.Ui.Base.Sounds;
global using WarpTextures = DevilDaggersInfo.App.Ui.Base.Textures;
