global using System;
global using System.Collections.Generic;
global using System.Numerics;
global using static DevilDaggersInfo.App.Engine.Graphics;
global using Shader = DevilDaggersInfo.App.Engine.Content.Shader;
global using WarpBlobs = DevilDaggersInfo.App.Ui.Base.Blobs;
global using WarpCharsets = DevilDaggersInfo.App.Ui.Base.Charsets;
global using WarpModels = DevilDaggersInfo.App.Ui.Base.Models;
global using WarpShaders = DevilDaggersInfo.App.Ui.Base.Shaders;
global using WarpShaderUniformInitializer = DevilDaggersInfo.App.Ui.Base.ShaderUniformInitializer;
global using WarpTextures = DevilDaggersInfo.App.Ui.Base.Textures;
