global using System;
global using System.Collections.Generic;
global using System.Numerics;
global using Warp.NET;
global using Warp.NET.Numerics;
global using static Warp.NET.Graphics;
global using DdInfoToolsBaseModels = DevilDaggersInfo.App.Ui.Base.Models;
global using DdInfoToolsBaseShaders = DevilDaggersInfo.App.Ui.Base.Shaders;
global using DdInfoToolsBaseShaderUniformInitializer = DevilDaggersInfo.App.Ui.Base.ShaderUniformInitializer;
global using DdInfoToolsBaseTextures = DevilDaggersInfo.App.Ui.Base.Textures;
global using Shader = Warp.NET.Content.Shader;
global using Texture = Warp.NET.Content.Texture;
global using WarpRenderImplUiCharsets = Warp.NET.RenderImpl.Ui.Charsets;
global using WarpRenderImplUiShaders = Warp.NET.RenderImpl.Ui.Shaders;
global using WarpRenderImplUiShaderUniformInitializer = Warp.NET.RenderImpl.Ui.ShaderUniformInitializer;
global using WarpRenderImplUiTextures = Warp.NET.RenderImpl.Ui.Textures;
