// ReSharper disable StringLiteralTypo
namespace DevilDaggersInfo.Web.Server.Utils.AssetInfo;

public static class AudioAudio
{
	public static AssetInfoEntry[] All { get; } =
	[
		new("andrasimpact", "Unused", ["Andras", "Enemy", "Unused"]),
		new("andrasrise", "Unused", ["Andras", "Enemy", "Unused"]),
		new("burrowcentipede", "Centipede burrow", ["Centipede", "Enemy", "Underground"]),
		new("chatterandras", "Unused", ["Andras", "Chatter", "Enemy", "Unused"]),
		new("chattercentipede", "Centipede chatter", ["Centipede", "Chatter", "Enemy"]),
		new("chattercentipede2", "Gigapede chatter", ["Chatter", "Enemy", "Gigapede"]),
		new("chattergigaspider", "Spider II chatter", ["Chatter", "Enemy", "Spider II"]),
		new("chatterleviathan", "Leviathan chatter", ["Chatter", "Enemy", "Leviathan"]),
		new("chatterminisquid", "Squid I chatter", ["Chatter", "Enemy", "Squid I"]),
		new("chatterskull", "Skull I chatter", ["Chatter", "Enemy", "Skull I"]),
		new("chatterskull2", "Skull II chatter", ["Chatter", "Enemy", "Skull II"]),
		new("chatterskull2black", "Transmuted Skull II chatter", ["Chatter", "Enemy", "Transmuted Skull II"]),
		new("chatterskull3", "Skull III chatter", ["Chatter", "Enemy", "Skull III"]),
		new("chatterskull3black", "Transmuted Skull III chatter", ["Chatter", "Enemy", "Transmuted Skull III"]),
		new("chatterskull4", "Skull IV chatter", ["Chatter", "Enemy", "Skull IV"]),
		new("chatterskull4black", "Transmuted Skull IV chatter", ["Chatter", "Enemy", "Transmuted Skull IV"]),
		new("chatterskullblack", "Transmuted Skull I chatter", ["Chatter", "Enemy", "Transmuted Skull I"]),
		new("chatterspider", "Spider I chatter", ["Chatter", "Enemy", "Spider I"]),
		new("chatterspiderling", "Spiderling chatter", ["Chatter", "Enemy", "Spiderling"]),
		new("chattersquid", "Squid II chatter", ["Chatter", "Enemy", "Squid II"]),
		new("chattersquidsmall", "Unused", ["Unused"]),
		new("chattersquidultra", "Squid III chatter", ["Chatter", "Enemy", "Squid III"]),
		new("chatterthorn", "Thorn chatter", ["Chatter", "Enemy", "Thorn"]),
		new("chatterultrapede", "Ghostpede chatter", ["Chatter", "Enemy", "Ghostpede"]),
		new("collectgib1", "Unused?", ["Unused"]),
		new("collectgib2", "Unused?", ["Unused"]),
		new("collectgib3", "Unused?", ["Unused"]),
		new("collectgibbase1", "Unused?", ["Unused"]),
		new("collectgibbase2", "Unused?", ["Unused"]),
		new("collectgibbase3", "Unused?", ["Unused"]),
		new("daggercall", "Pleb Dagger in lobby", ["Dagger", "Lobby", "Pleb"]),
		new("daggercall1bronze", "Bronze Dagger in lobby", ["Bronze", "Dagger", "Lobby"]),
		new("daggercall2silver", "Silver Dagger in lobby", ["Dagger", "Lobby", "Silver"]),
		new("daggercall3gold", "Golden Dagger in lobby", ["Dagger", "Golden", "Lobby"]),
		new("daggercall4devil", "Devil Dagger in lobby", ["Dagger", "Devil", "Lobby"]),
		new("daggercall5", "Leviathan Dagger in lobby", ["Dagger", "Leviathan", "Lobby"]),
		new("daggercollect", "Dagger lobby grab", ["Dagger", "Lobby"]),
		new("daggercollect1bronze", "Bronze Dagger unlock", ["Bronze", "Dagger", "Unlock"]),
		new("daggercollect2silver", "Silver Dagger unlock", ["Dagger", "Silver", "Unlock"]),
		new("daggercollect3gold", "Golden Dagger unlock", ["Dagger", "Golden", "Unlock"]),
		new("daggercollect4devil", "Devil Dagger unlock", ["Dagger", "Devil", "Unlock"]),
		new("daggercollect5", "Leviathan Dagger unlock", ["Dagger", "Leviathan", "Unlock"]),
		new("daggerdivert", "Unused (Andras?)", ["Unused"]),
		new("daggerdrone", "Level 3 homing dagger noise", ["Homing dagger", "Level 3"]),
		new("daggerhit1", "Default dagger hit", ["Normal dagger"]),
		new("daggerseek", "Level 4 homing dagger fire", ["Homing dagger", "Level 4"]),
		new("daggersteal1", "Unused", ["Unused"]),
		new("daggersteal2", "Unused", ["Unused"]),
		new("daggersteal3", "Unused", ["Unused"]),
		new("daggersteal4", "Unused", ["Unused"]),
		new("daggersteal5", "Unused", ["Unused"]),
		new("damageandras", "Unused", ["Andras", "Damage", "Enemy", "Unused"]),
		new("damagecentipede", "Centipede gem is damaged", ["Centipede", "Damage", "Enemy"]),
		new("damagecentipede2", "Gigapede gem is damaged", ["Damage", "Enemy", "Gigapede"]),
		new("damagegigaspider", "Spider II damage", ["Damage", "Enemy", "Spider II"]),
		new("damageleviathan", "Leviathan gem comes off", ["Damage", "Enemy", "Leviathan"]),
		new("damagespider", "Spider I damage", ["Damage", "Enemy", "Spider I"]),
		new("damagesquid", "Squid I / II / III / Leviathan gem damage", ["Damage", "Enemy", "Leviathan", "Squid I", "Squid II", "Squid III"]),
		new("damagesquid2", "Squid II gem comes off", ["Damage", "Enemy", "Squid II"]),
		new("damagesquid3", "Squid III gem comes off", ["Damage", "Enemy", "Squid III"]),
		new("damagesquid4", "Unused", ["Unused"]),
		new("damagethorn", "Thorn damage", ["Damage", "Enemy", "Thorn"]),
		new("damageultrapede", "Ghostpede gem comes off", ["Damage", "Enemy", "Ghostpede"]),
		new("death", "Player death from enemy", ["Death", "Player"]),
		new("eggbounce", "Spider Egg I / Spider Egg II bounce on floor", ["Enemy", "Spider Egg I", "Spider Egg II"]),
		new("eggburst", "Spider Egg I / Spider Egg II burst (hatch or death)", ["Death", "Enemy", "Spider Egg I", "Spider Egg II"]),
		new("eggburst2", "Unused", ["Unused"]),
		new("eggdrone", "Spider Egg I chatter", ["Chatter", "Enemy", "Spider Egg I"]),
		new("eggdrone2", "Spider Egg II chatter", ["Chatter", "Enemy", "Spider Egg II"]),
		new("eyearouse", "Orb is locating Player", ["Enemy", "Orb"]),
		new("eyearousedrone", "Orb sees Player", ["Enemy", "Orb"]),
		new("eyehit", "Orb damage", ["Damage", "Enemy", "Orb"]),
		new("eyepacifydrone", "Unused", ["Unused"]),
		new("fall", "Player death from falling", ["Death", "Player"]),
		new("gibcollect", "Gem collect during Level 1 / 2 / 4", ["Gem"]),
		new("gibcollectmagic", "Gem collect during Level 3", ["Gem"]),
		new("gibdrone1", "Gem idle?", ["Gem"]),
		new("gibdrone2", "Gem idle?", ["Gem"]),
		new("gibdrone3", "Gem idle?", ["Gem"]),
		new("gigaricochet1", "Level 3 / 4 normal dagger ricochet", ["Level 3", "Level 4", "Normal dagger", "Ricochet"]),
		new("gigaricochet2", "Level 3 / 4 normal dagger ricochet", ["Level 3", "Level 4", "Normal dagger", "Ricochet"]),
		new("gigaricochet3", "Level 3 / 4 normal dagger ricochet", ["Level 3", "Level 4", "Normal dagger", "Ricochet"]),
		new("gigaricochet4", "Level 3 / 4 normal dagger ricochet", ["Level 3", "Level 4", "Normal dagger", "Ricochet"]),
		new("gigaricochet5", "Level 3 / 4 normal dagger ricochet", ["Level 3", "Level 4", "Normal dagger", "Ricochet"]),
		new("highscore1", "Plays when beating your highscore.", ["Highscore"]),
		new("highscore2", "Plays 10 seconds before beating next person on friends leaderboard.", ["Highscore"]),
		new("jump1", "Player jump", ["Player"]),
		new("jump2", "Player bunnyhop", ["Player"]),
		new("jump3", "Player precise bunnyhop", ["Player"]),
		new("killandras", "Unused", ["Andras", "Death", "Enemy", "Unused"]),
		new("killcentipede", "Centipede death", ["Centipede", "Death", "Enemy"]),
		new("killcentipede2", "Gigapede death", ["Death", "Enemy", "Gigapede"]),
		new("killeye", "Orb death", ["Death", "Enemy", "Orb"]),
		new("killgigaspider", "Spider II death", ["Death", "Enemy", "Spider II"]),
		new("killleviathan", "Leviathan death", ["Death", "Enemy", "Leviathan"]),
		new("killminisquid", "Squid I death", ["Death", "Enemy", "Squid I"]),
		new("killskull1", "Skull I death", ["Death", "Enemy", "Skull I"]),
		new("killskull2", "Skull I death", ["Death", "Enemy", "Skull I"]),
		new("killskull3", "Skull I death", ["Death", "Enemy", "Skull I"]),
		new("killskull4", "Skull I death", ["Death", "Enemy", "Skull I"]),
		new("killskull5", "Skull I death", ["Death", "Enemy", "Skull I"]),
		new("killskullblack1", "Transmuted Skull I death", ["Death", "Enemy", "Transmuted Skull I"]),
		new("killskullblack2", "Transmuted Skull I death", ["Death", "Enemy", "Transmuted Skull I"]),
		new("killskullblack3", "Transmuted Skull I death", ["Death", "Enemy", "Transmuted Skull I"]),
		new("killskullblack4", "Transmuted Skull I death", ["Death", "Enemy", "Transmuted Skull I"]),
		new("killspider", "Spider I death", ["Death", "Enemy", "Spider I"]),
		new("killspiderling1", "Spiderling death", ["Death", "Enemy", "Spiderling"]),
		new("killspiderling2", "Spiderling death", ["Death", "Enemy", "Spiderling"]),
		new("killspiderling3", "Spiderling death", ["Death", "Enemy", "Spiderling"]),
		new("killspiderling4", "Spiderling death", ["Death", "Enemy", "Spiderling"]),
		new("killspiderling5", "Spiderling death", ["Death", "Enemy", "Spiderling"]),
		new("killsquid", "Squid II death", ["Death", "Enemy", "Squid II"]),
		new("killsuperskull", "Skull II death", ["Death", "Enemy", "Skull II"]),
		new("killsuperskull2", "Skull III death", ["Death", "Enemy", "Skull III"]),
		new("killsuperskull2black", "Transmuted Skull III death", ["Death", "Enemy", "Transmuted Skull III"]),
		new("killsuperskull3", "Skull IV death / Transmuted Skull IV death", ["Death", "Enemy", "Skull IV", "Transmuted Skull IV"]),
		new("killsuperskullblack", "Transmuted Skull II death", ["Death", "Enemy", "Transmuted Skull II"]),
		new("killthorn", "Thorn death", ["Death", "Enemy", "Thorn"]),
		new("killultraskull", "Unused", ["Unused"]),
		new("killultrasquid", "Squid III death", ["Death", "Enemy", "Squid III"]),
		new("land", "Land sound for Player", ["Player"]),
		new("land2", "Land sound for Player", ["Player"]),
		new("legends", "Easter egg music for skull thrones", ["Lobby", "Music"]),
		new("leveldown", "Unused", ["Unused"]),
		new("levelup2", "Level 2 upgrade", ["Level 2", "Player", "Upgrade"]),
		new("levelup3", "Level 3 upgrade", ["Level 3", "Player", "Upgrade"]),
		new("levelup4", "Level 4 upgrade", ["Level 4", "Player", "Upgrade"]),
		new("leviathanbeckon", "Leviathan / Orb beckon", ["Enemy", "Leviathan", "Orb"]),
		new("leviathanbeckon2", "Plays when a skull touches Leviathan's or Orb's beckon ring.", ["Enemy", "Leviathan", "Skull I", "Skull II", "Skull III", "Skull IV", "Orb"]),
		new("leviathantransmute", "Plays when a skull is transmuted by Leviathan (and Orb?).", ["Enemy", "Leviathan", "Orb", "Transmuted Skull I", "Transmuted Skull II", "Transmuted Skull III", "Transmuted Skull IV"]),
		new("magentadetonate1", "Level 4 homing dagger explode", ["Homing dagger", "Level 4"]),
		new("magentadetonate2", "Level 4 homing dagger explode", ["Homing dagger", "Level 4"]),
		new("magentadetonate3", "Level 4 homing dagger explode", ["Homing dagger", "Level 4"]),
		new("magentadetonate4", "Level 4 homing dagger explode", ["Homing dagger", "Level 4"]),
		new("magentadetonate5", "Level 4 homing dagger explode", ["Homing dagger", "Level 4"]),
		new("magentadrone", "Level 4 homing dagger noise", ["Homing dagger", "Level 4"]),
		new("magentashot", "Level 4 homing dagger shotgun", ["Homing dagger", "Level 4", "Shot"]),
		new("magentastuckenemy1", "Level 4 homing dagger pierces an enemy", ["Dagger pierce", "Homing dagger", "Level 4"]),
		new("magentastuckenemy2", "Level 4 homing dagger pierces an enemy", ["Dagger pierce", "Homing dagger", "Level 4"]),
		new("magentastuckenemy3", "Level 4 homing dagger pierces an enemy", ["Dagger pierce", "Homing dagger", "Level 4"]),
		new("magentastuckenemy4", "Level 4 homing dagger pierces an enemy", ["Dagger pierce", "Homing dagger", "Level 4"]),
		new("magentastuckenemy5", "Level 4 homing dagger pierces an enemy", ["Dagger pierce", "Homing dagger", "Level 4"]),
		new("magicpierce1", "Level 3 homing dagger pierces an enemy", ["Dagger pierce", "Homing dagger", "Level 3"]),
		new("magicpierce2", "Level 3 homing dagger pierces an enemy", ["Dagger pierce", "Homing dagger", "Level 3"]),
		new("magicpierce3", "Level 3 homing dagger pierces an enemy", ["Dagger pierce", "Homing dagger", "Level 3"]),
		new("magicpierce4", "Level 3 homing dagger pierces an enemy", ["Dagger pierce", "Homing dagger", "Level 3"]),
		new("magicpierce5", "Level 3 homing dagger pierces an enemy", ["Dagger pierce", "Homing dagger", "Level 3"]),
		new("magicpulse", "Unused", ["Unused"]),
		new("meat1", "Small meat bounce on floor", ["Gore"]),
		new("meat10", "Small meat bounce on floor", ["Gore"]),
		new("meat11", "Small meat bounce on floor", ["Gore"]),
		new("meat12", "Small meat bounce on floor", ["Gore"]),
		new("meat13", "Small meat bounce on floor", ["Gore"]),
		new("meat2", "Small meat bounce on floor", ["Gore"]),
		new("meat3", "Small meat bounce on floor", ["Gore"]),
		new("meat4", "Small meat bounce on floor", ["Gore"]),
		new("meat5", "Small meat bounce on floor", ["Gore"]),
		new("meat6", "Small meat bounce on floor", ["Gore"]),
		new("meat7", "Small meat bounce on floor", ["Gore"]),
		new("meat8", "Small meat bounce on floor", ["Gore"]),
		new("meat9", "Small meat bounce on floor", ["Gore"]),
		new("meatbig1", "Big meat bounce on floor", ["Gore"]),
		new("meatbig2", "Big meat bounce on floor", ["Gore"]),
		new("meatbig3", "Big meat bounce on floor", ["Gore"]),
		new("meatbig4", "Big meat bounce on floor", ["Gore"]),
		new("meatbig5", "Big meat bounce on floor", ["Gore"]),
		new("meatbig6", "Big meat bounce on floor", ["Gore"]),
		new("meatmed1", "Medium meat bounce on floor", ["Gore"]),
		new("meatmed2", "Medium meat bounce on floor", ["Gore"]),
		new("meatmed3", "Medium meat bounce on floor", ["Gore"]),
		new("meatmed4", "Medium meat bounce on floor", ["Gore"]),
		new("meatmed5", "Medium meat bounce on floor", ["Gore"]),
		new("meatmed6", "Medium meat bounce on floor", ["Gore"]),
		new("menuatmos", "Main menu music", ["Music"]),
		new("menutheme", "Devil Daggers splash screen music", ["Music"]),
		new("polarity1e", "Arena east", ["Arena"]),
		new("polarity2w", "Arena west", ["Arena"]),
		new("polarity3n", "Arena north", ["Arena"]),
		new("polarity4s", "Arena south", ["Arena"]),
		new("rapid1", "Level 1 normal dagger spray", ["Level 1", "Normal dagger", "Spray"]),
		new("rapid2", "Level 2 normal dagger spray", ["Level 2", "Normal dagger", "Spray"]),
		new("rapid3", "Level 3 normal dagger spray", ["Level 3", "Normal dagger", "Spray"]),
		new("rapid4", "Level 4 normal dagger spray", ["Level 4", "Normal dagger", "Spray"]),
		new("ricochet1", "Level 1 normal dagger ricochet", ["Level 1", "Normal dagger", "Ricochet"]),
		new("ricochet2", "Level 1 normal dagger ricochet", ["Level 1", "Normal dagger", "Ricochet"]),
		new("ricochet3", "Level 1 normal dagger ricochet", ["Level 1", "Normal dagger", "Ricochet"]),
		new("ricochet4", "Level 1 normal dagger ricochet", ["Level 1", "Normal dagger", "Ricochet"]),
		new("ricochet5", "Level 1 normal dagger ricochet", ["Level 1", "Normal dagger", "Ricochet"]),
		new("ricochetmagenta1", "Level 4 homing dagger ricochet", ["Homing dagger", "Level 4", "Ricochet"]),
		new("ricochetmagenta2", "Level 4 homing dagger ricochet", ["Homing dagger", "Level 4", "Ricochet"]),
		new("ricochetmagenta3", "Level 4 homing dagger ricochet", ["Homing dagger", "Level 4", "Ricochet"]),
		new("ricochetmagenta4", "Level 4 homing dagger ricochet", ["Homing dagger", "Level 4", "Ricochet"]),
		new("ricochetmagenta5", "Level 4 homing dagger ricochet", ["Homing dagger", "Level 4", "Ricochet"]),
		new("ricochetmagic1", "Level 3 homing dagger ricochet", ["Homing dagger", "Level 3", "Ricochet"]),
		new("ricochetmagic2", "Level 3 homing dagger ricochet", ["Homing dagger", "Level 3", "Ricochet"]),
		new("ricochetmagic3", "Level 3 homing dagger ricochet", ["Homing dagger", "Level 3", "Ricochet"]),
		new("ricochetmagic4", "Level 3 homing dagger ricochet", ["Homing dagger", "Level 3", "Ricochet"]),
		new("ricochetmed1", "Level 2 normal dagger ricochet", ["Level 2", "Normal dagger", "Ricochet"]),
		new("ricochetmed2", "Level 2 normal dagger ricochet", ["Level 2", "Normal dagger", "Ricochet"]),
		new("ricochetmed3", "Level 2 normal dagger ricochet", ["Level 2", "Normal dagger", "Ricochet"]),
		new("ricochetmed4", "Level 2 normal dagger ricochet", ["Level 2", "Normal dagger", "Ricochet"]),
		new("ricochetmed5", "Level 2 normal dagger ricochet", ["Level 2", "Normal dagger", "Ricochet"]),
		new("secretsnake", "Unused", ["Unused"]),
		new("secretsnake2", "Plays when discovering an easter egg in the lobby.", ["Easter Egg", "Lobby"]),
		new("shard1", "Orb shard bounce on floor", ["Enemy", "Orb"]),
		new("shard2", "Orb shard bounce on floor", ["Enemy", "Orb"]),
		new("shard3", "Orb shard bounce on floor", ["Enemy", "Orb"]),
		new("shard4", "Orb shard bounce on floor", ["Enemy", "Orb"]),
		new("shard5", "Orb shard bounce on floor", ["Enemy", "Orb"]),
		new("shot1", "Level 1 normal dagger shotgun", ["Level 1", "Normal dagger", "Shot"]),
		new("shot2", "Level 2 normal dagger shotgun", ["Level 2", "Normal dagger", "Shot"]),
		new("shot3", "Unused", ["Unused"]),
		new("shot3alt1", "Level 3 normal dagger shotgun", ["Level 3", "Normal dagger", "Shot"]),
		new("shot3alt2", "Level 3 normal dagger shotgun", ["Level 3", "Normal dagger", "Shot"]),
		new("shot3alt3", "Level 3 normal dagger shotgun", ["Level 3", "Normal dagger", "Shot"]),
		new("shot3alt4", "Level 3 normal dagger shotgun", ["Level 3", "Normal dagger", "Shot"]),
		new("shot4alt1", "Level 4 normal dagger shotgun", ["Level 4", "Normal dagger", "Shot"]),
		new("shot4alt2", "Level 4 normal dagger shotgun", ["Level 4", "Normal dagger", "Shot"]),
		new("shot4alt3", "Level 4 normal dagger shotgun", ["Level 4", "Normal dagger", "Shot"]),
		new("shot4alt4", "Level 4 normal dagger shotgun", ["Level 4", "Normal dagger", "Shot"]),
		new("shot4alt5", "Level 4 normal dagger shotgun", ["Level 4", "Normal dagger", "Shot"]),
		new("skullaggro", "Unused", ["Unused"]),
		new("skullclop1", "Skull bounce on floor or with other skull", ["Enemy", "Skull I", "Skull III"]),
		new("skullclop2", "Skull bounce on floor or with other skull", ["Enemy", "Skull I", "Skull III"]),
		new("skullclop3", "Skull bounce on floor or with other skull", ["Enemy", "Skull I", "Skull III"]),
		new("skullclop4", "Skull bounce on floor or with other skull", ["Enemy", "Skull I", "Skull III"]),
		new("skullclop5", "Skull bounce on floor or with other skull", ["Enemy", "Skull I", "Skull III"]),
		new("skullclop6", "Skull bounce on floor or with other skull", ["Enemy", "Skull I", "Skull III"]),
		new("sorathlogo", "Sorath splash screen sound", ["Splash screen"]),
		new("sorathlogo2", "Unused", ["Unused"]),
		new("sorathstone", "Sorath stone easter egg music", ["Lobby", "Music"]),
		new("spawnandras", "Unused", ["Andras", "Enemy", "Spawn", "Unused"]),
		new("spawncentipede", "Centipede spawn", ["Centipede", "Enemy", "Spawn"]),
		new("spawncentipede2", "Gigapede spawn", ["Enemy", "Gigapede", "Spawn"]),
		new("spawnegg", "Spider I / Spider II shoot egg", ["Enemy", "Spawn", "Spider I", "Spider II"]),
		new("spawngigaspider", "Spider II spawn", ["Enemy", "Spawn", "Spider II"]),
		new("spawnleviathan", "Leviathan spawn", ["Enemy", "Leviathan", "Spawn"]),
		new("spawnminisquid", "Squid I spawn", ["Enemy", "Spawn", "Squid I"]),
		new("spawnplayer", "Player spawn", ["Player", "Spawn"]),
		new("spawnskulls", "Squid II gush (yes, really)", ["Enemy", "Spawn", "Squid II"]),
		new("spawnskulls2", "Squid I gush (yes, really)", ["Enemy", "Spawn", "Squid I"]),
		new("spawnskulls3", "Squid III gush", ["Enemy", "Spawn", "Squid III"]),
		new("spawnspider", "Spider I spawn", ["Enemy", "Spawn", "Spider I"]),
		new("spawnsquid", "Squid II spawn", ["Enemy", "Spawn", "Squid II"]),
		new("spawnultrapede", "Ghostpede spawn", ["Enemy", "Ghostpede", "Spawn"]),
		new("spawnultrasquid", "Squid III spawn", ["Enemy", "Spawn", "Squid III"]),
		new("spidereat1", "Spider I / Spider II eat gem", ["Enemy", "Spider I", "Spider II"]),
		new("spidereat2", "Spider I / Spider II eat gem", ["Enemy", "Spider I", "Spider II"]),
		new("spidereat3", "Spider I / Spider II eat gem", ["Enemy", "Spider I", "Spider II"]),
		new("spidereat4", "Spider I / Spider II eat gem", ["Enemy", "Spider I", "Spider II"]),
		new("spidereat5", "Spider I / Spider II eat gem", ["Enemy", "Spider I", "Spider II"]),
		new("spidereat6", "Spider I / Spider II eat gem", ["Enemy", "Spider I", "Spider II"]),
		new("splashgiga", "Squid II death splash", ["Death splash", "Enemy", "Squid II"]),
		new("splashgiga2", "Centipede / Gigapede death splash", ["Centipede", "Death splash", "Enemy", "Gigapede"]),
		new("splashgiga3", "Spider I death splash", ["Death splash", "Enemy", "Spider I"]),
		new("splashgiga4", "Squid III death splash", ["Death splash", "Enemy", "Squid III"]),
		new("splashgiga5", "Spider II death splash", ["Death splash", "Enemy", "Spider II"]),
		new("splashgiga6", "Ghostpede death splash", ["Death splash", "Enemy", "Ghostpede"]),
		new("stealgib", "Gem attracted by Spider I", ["Gem"]),
		new("stealgib2", "Gem attracted by Spider II", ["Gem"]),
		new("subchattercentipede", "Centipede / Gigapede / Ghostpede underground", ["Centipede", "Enemy", "Ghostpede", "Gigapede", "Underground"]),
		new("thornemerge", "Thorn spawn", ["Enemy", "Thorn", "Underground"]),
		new("thorngib1", "Unused", ["Unused"]),
		new("thorngib2", "Unused", ["Unused"]),
		new("thorngib3", "Unused", ["Unused"]),
		new("thorngib4", "Unused", ["Unused"]),
		new("thorngib5", "Unused", ["Unused"]),
		new("thorngib6", "Unused", ["Unused"]),
		new("uiclick", "User interface click", ["UI"]),
		new("uihover", "User interface hover", ["UI"]),
		new("uislider", "User interface slider", ["UI"]),
		new("ultrapedecrash", "Ghostpede collide with floor", ["Enemy", "Ghostpede"]),
		new("ultrapedeeat", "Ghostpede eat homing dagger", ["Enemy", "Ghostpede"]),
		new("ultrapedefall", "Ghostpede death", ["Death", "Enemy", "Ghostpede"]),
		new("unburrowcentipede", "Centipede emerge", ["Centipede", "Enemy", "Underground"]),
	];
}
