// ReSharper disable StringLiteralTypo
namespace DevilDaggersInfo.Web.Server.Utils.AssetInfo;

public static class DdMeshes
{
	public static AssetInfoEntry[] All { get; } =
	[
		new("bat", "?", ["?"]),
		new("blood1", "?", ["?"]),
		new("blood10", "?", ["?"]),
		new("blood11", "?", ["?"]),
		new("blood2", "?", ["?"]),
		new("blood3", "?", ["?"]),
		new("blood4", "?", ["?"]),
		new("blood5", "?", ["?"]),
		new("blood6", "?", ["?"]),
		new("blood7", "?", ["?"]),
		new("blood8", "?", ["?"]),
		new("blood9", "?", ["?"]),
		new("boid", "Skull I", ["Enemy", "Skull I"]),
		new("boid2", "Skull II", ["Enemy", "Skull II"]),
		new("boid2horns", "Skull II horns", ["Enemy", "Horns", "Skull II"]),
		new("boid3", "Skull III", ["Enemy", "Skull III"]),
		new("boid3horns", "Skull III horns", ["Enemy", "Horns", "Skull III"]),
		new("boid3jaw", "Skull III jaw", ["Enemy", "Jaw", "Skull III"]),
		new("boid4", "Skull IV", ["Enemy", "Skull IV"]),
		new("boid4jaw", "Skull IV jaw", ["Enemy", "Jaw", "Skull IV"]),
		new("bottom", "?", ["?"]),
		new("dagger", "Dagger", ["Dagger"]),
		new("ember1", "?", ["?"]),
		new("ember2", "?", ["?"]),
		new("ember3", "?", ["?"]),
		new("feather1", "?", ["?"]),
		new("feather2", "?", ["?"]),
		new("flame1", "?", ["?"]),
		new("flame2", "?", ["?"]),
		new("flame3", "?", ["?"]),
		new("flame4", "?", ["?"]),
		new("flame5", "?", ["?"]),
		new("flame6", "?", ["?"]),
		new("flame7", "?", ["?"]),
		new("flame8", "?", ["?"]),
		new("gib", "Gem", ["Gem"]),
		new("gib1", "?", ["?"]),
		new("gib2", "?", ["?"]),
		new("gib3", "?", ["?"]),
		new("gigaegg", "Spider Egg II", ["Enemy", "Spider Egg II"]),
		new("gigaspiderbody", "?", ["?"]),
		new("gigaspidercrest", "?", ["?"]),
		new("gigaspiderfangs", "?", ["?"]),
		new("gigaspiderfangs2", "?", ["?"]),
		new("gigaspiderhead", "?", ["?"]),
		new("gigaspiderhorns", "?", ["?"]),
		new("gigaspiderjaw", "?", ["?"]),
		new("gigaspiderpalm", "?", ["?"]),
		new("hand", "Level 1 player hand (right)", ["Level 1", "Player"]),
		new("hand2", "Level 2 player hand (right)", ["Level 2", "Player"]),
		new("hand2left", "Level 2 player hand (left)", ["Level 2", "Player"]),
		new("hand3", "Level 3 player hand (right)", ["Level 3", "Player"]),
		new("hand3left", "Level 3 player hand (left)", ["Level 3", "Player"]),
		new("hand4", "Level 4 player hand (right)", ["Level 4", "Player"]),
		new("hand4left", "Level 4 player hand (left)", ["Level 4", "Player"]),
		new("handleft", "Level 1 player hand (left)", ["Level 1", "Player"]),
		new("immortalorb", "?", ["?"]),
		new("levicrown", "?", ["?"]),
		new("levicrown2", "?", ["?"]),
		new("levicrown2jaw", "?", ["?"]),
		new("levicrownjaw", "?", ["?"]),
		new("levideath", "?", ["?"]),
		new("levidividerskull", "?", ["?"]),
		new("levigem", "?", ["?"]),
		new("levigem2", "?", ["?"]),
		new("leviorb", "?", ["?"]),
		new("leviskull", "?", ["?"]),
		new("leviskull2", "?", ["?"]),
		new("leviskulljaw", "?", ["?"]),
		new("levitent", "?", ["?"]),
		new("levitent2", "?", ["?"]),
		new("light_sphere", "?", ["?"]),
		new("logodagger", "?", ["?"]),
		new("logohand", "?", ["?"]),
		new("minisquidcrest", "?", ["?"]),
		new("minisquidcrestskull", "?", ["?"]),
		new("minisquidgem", "?", ["?"]),
		new("minisquidhorns", "?", ["?"]),
		new("minisquidjaw", "?", ["?"]),
		new("minisquidjawskull", "?", ["?"]),
		new("orbgib1", "?", ["?"]),
		new("orbgib10", "?", ["?"]),
		new("orbgib11", "?", ["?"]),
		new("orbgib12", "?", ["?"]),
		new("orbgib13", "?", ["?"]),
		new("orbgib14", "?", ["?"]),
		new("orbgib15", "?", ["?"]),
		new("orbgib16", "?", ["?"]),
		new("orbgib2", "?", ["?"]),
		new("orbgib3", "?", ["?"]),
		new("orbgib4", "?", ["?"]),
		new("orbgib5", "?", ["?"]),
		new("orbgib6", "?", ["?"]),
		new("orbgib7", "?", ["?"]),
		new("orbgib8", "?", ["?"]),
		new("orbgib9", "?", ["?"]),
		new("owlwing", "?", ["?"]),
		new("pedebody", "?", ["?"]),
		new("pedehead", "?", ["?"]),
		new("pedejaw", "?", ["?"]),
		new("pedeleg1", "?", ["?"]),
		new("pedeleg2", "?", ["?"]),
		new("pedeleg3", "?", ["?"]),
		new("pedetail", "?", ["?"]),
		new("pedetaillegs", "?", ["?"]),
		new("pedeweak", "?", ["?"]),
		new("pillar", "?", ["?"]),
		new("plane400", "?", ["?"]),
		new("rubble", "?", ["?"]),
		new("smokeblob1", "?", ["?"]),
		new("smokeblob2", "?", ["?"]),
		new("smokeblob3", "?", ["?"]),
		new("smokeblob4", "?", ["?"]),
		new("sorathstone", "?", ["?"]),
		new("spiderbody", "?", ["?"]),
		new("spideregg1", "Spider Egg I", ["Enemy", "Spider Egg I"]),
		new("spideregg2", "Unused? (Same as 'gib')", ["Unused"]),
		new("spiderfangs", "?", ["?"]),
		new("spidergib", "?", ["?"]),
		new("spiderhead", "?", ["?"]),
		new("spiderjaw", "?", ["?"]),
		new("spiderleg1", "?", ["?"]),
		new("spiderleg1f", "?", ["?"]),
		new("spiderleg2", "?", ["?"]),
		new("spiderleg2f", "?", ["?"]),
		new("spiderleg3", "?", ["?"]),
		new("spiderleg3f", "?", ["?"]),
		new("spiderling", "?", ["?"]),
		new("spiderlingleg1", "?", ["?"]),
		new("spiderlingleg2", "?", ["?"]),
		new("spiderlingleg3", "?", ["?"]),
		new("spiderlingpalms", "?", ["?"]),
		new("spiderpalm", "?", ["?"]),
		new("spiderpalmf", "?", ["?"]),
		new("squidarm", "?", ["?"]),
		new("squidcrest", "?", ["?"]),
		new("squidcrestskull", "?", ["?"]),
		new("squidgem", "?", ["?"]),
		new("squidhorns", "?", ["?"]),
		new("squidjaws", "?", ["?"]),
		new("squidjawskull", "?", ["?"]),
		new("squidteeth", "?", ["?"]),
		new("statue1", "?", ["?"]),
		new("statue2", "?", ["?"]),
		new("statue3", "?", ["?"]),
		new("thorn", "?", ["?"]),
		new("thorngib1", "?", ["?"]),
		new("thorngib2", "?", ["?"]),
		new("thorngib3", "?", ["?"]),
		new("tile", "?", ["?"]),
		new("tile2", "?", ["?"]),
		new("ultrapedecrown", "?", ["?"]),
		new("ultrasquidcrest", "?", ["?"]),
		new("ultrasquidcrestskull", "?", ["?"]),
		new("ultrasquidgem", "?", ["?"]),
		new("ultrasquidhorns", "?", ["?"]),
		new("ultrasquidjaw", "?", ["?"]),
		new("ultrasquidjawskull", "?", ["?"]),
		new("ultrasquidteeth", "?", ["?"]),
		new("ultrasquidtent", "?", ["?"]),
	];
}
