// ReSharper disable StringLiteralTypo
namespace DevilDaggersInfo.Web.Server.Utils.AssetInfo;

public static class DdObjectBindings
{
	public static AssetInfoEntry[] All { get; } =
	[
		new("bat", "Unused", ["?"]),
		new("boid", "Pede heads and tail / Spiders pedipalps", ["Spider I", "Spider II", "Centipede", "Gigapede", "Ghostpede"]),
		new("boid_pop", "Unused?", ["?"]),
		new("dagger", "Pleb lobby dagger", ["Dagger", "Pleb"]),
		new("dagger1", "Level 1 dagger", ["Dagger", "Level 1"]),
		new("dagger2", "Level 2 dagger", ["Dagger", "Level 2"]),
		new("dagger3", "Level 3 regular dagger", ["Dagger", "Level 3"]),
		new("dagger4", "Level 3 homing dagger", ["Dagger", "Level 3", "Homing"]),
		new("dagger5", "Level 4 regular dagger", ["Dagger", "Level 4"]),
		new("dagger6", "Level 4 homing dagger", ["Dagger", "Level 4", "Homing"]),
		new("daggerbronze", "Bronze lobby dagger", ["Dagger", "Bronze"]),
		new("daggerdevil", "Devil lobby dagger", ["Dagger", "Devil"]),
		new("daggergold", "Golden lobby dagger", ["Dagger", "Golden"]),
		new("daggerlevi", "Leviathan lobby dagger", ["Dagger", "Leviathan"]),
		new("daggersilver", "Silver lobby dagger", ["Dagger", "Silver"]),
		new("gib", "Gems (including gems on enemies)", ["Gem"]),
		new("gibegg", "Blinking effect of gems close to active spiders", ["Gem"]),
		new("gigaegg", "Spider II egg goo", ["Spider Egg II", "Goo"]),
		new("hand", "Level 1 hand", ["Hand", "Level 1"]),
		new("hand0", "Lobby hand", ["Hand"]),
		new("hand2", "Level 2 hand", ["Hand", "Level 2"]),
		new("hand3", "Level 3 hand", ["Hand", "Level 3"]),
		new("hand4", "Level 3 hand flash", ["Hand", "Level 3"]),
		new("hand5", "Level 4 hand", ["Hand", "Level 4"]),
		new("hand6", "Level 4 hand flash", ["Hand", "Level 4"]),
		new("immortaleye", "Orb", ["Orb"]),
		new("immortaleyehit", "Orb damage", ["Orb", "Damage"]),
		new("levitent", "Leviathan antlers", ["Leviathan"]),
		new("levitentgib", "Leviathan antlers death", ["Leviathan", "Death"]),
		new("levitenthit", "Leviathan antlers damage", ["Leviathan", "Damage"]),
		new("leviwarp", "Leviathan antlers and divider skulls spawn effect", ["Leviathan"]),
		new("leviwarp2", "Leviathan skybox effect", ["Leviathan"]),
		new("leviwarp3", "Unused?", ["?"]),
		new("logodagger", "Title screen dagger", ["Title"]),
		new("logohand", "Title screen hand", ["Title"]),
		new("logotext", "Title", ["Title"]),
		new("minisquidarm", "Unused", ["?"]),
		new("particle", "Unused", ["?"]),
		new("particle2", "Unused", ["?"]),
		new("particle_decal", "Unused", ["?"]),
		new("pedebody", "Unused", ["?"]),
		new("pedehead", "Unused", ["?"]),
		new("pedejaw", "Unused", ["?"]),
		new("pedeleg1", "Unused", ["?"]),
		new("pedeleg2", "Unused", ["?"]),
		new("pedeleg3", "Unused", ["?"]),
		new("pedetail", "Unused", ["?"]),
		new("skullscroll", "?", ["?"]),
		new("skullwarp", "Unused", ["?"]),
		new("sorathlogo", "Splash screen logo", ["Splash screen"]),
		new("spideregg1", "Spider I egg goo", ["Spider Egg I", "Goo"]),
		new("spideregg2", "Spider I and II egg", ["Spider Egg I", "Spider Egg II"]),
		new("spidereggflash", "Flashing effect of spider eggs near hatching", ["Spider Egg I", "Spider Egg II"]),
		new("squidarm", "Unused", ["?"]),
		new("squidarmgib", "Unused", ["?"]),
		new("squidarmhit", "Unused", ["?"]),
		new("squidteeth", "Unused", ["?"]),
		new("squidteethgib", "Unused", ["?"]),
		new("squidteethhit", "Unused", ["?"]),
		new("thorn", "Thorn (excluding rubble)", ["Thorn"]),
		new("thornhit", "Thorn damage (excluding rubble)", ["Thorn"]),
		new("tile", "Unused", ["?"]),
		new("tile2", "Unused", ["?"]),
	];
}
