// ReSharper disable StringLiteralTypo
namespace DevilDaggersInfo.Web.Server.Utils.AssetInfo;

public static class DdShaders
{
	public static AssetInfoEntry[] All { get; } =
	[
		new("boid", "?", ["?"]),
		new("boid_batch", "?", ["?"]),
		new("boid_pop", "?", ["?"]),
		new("boid_pop_batch", "?", ["?"]),
		new("daggerlevi", "?", ["?"]),
		new("debug", "Unused?", ["?"]),
		new("default_texture", "?", ["?"]),
		new("depth", "?", ["?"]),
		new("egg", "?", ["?"]),
		new("gib", "?", ["?"]),
		new("gib_batch", "?", ["?"]),
		new("hand", "?", ["?"]),
		new("hand_batch", "?", ["?"]),
		new("light", "?", ["?"]),
		new("light_batch", "?", ["?"]),
		new("light_ring", "?", ["?"]),
		new("owlwing", "Unused?", ["?"]),
		new("particle", "?", ["?"]),
		new("particle2", "?", ["?"]),
		new("particle2_batch", "?", ["?"]),
		new("particle_decal", "?", ["?"]),
		new("particle_decal_batch", "?", ["?"]),
		new("post", "?", ["?"]),
		new("post_combine", "?", ["?"]),
		new("post_final", "?", ["?"]),
		new("post_title", "?", ["?"]),
		new("shadow", "?", ["?"]),
		new("shadow_batch", "?", ["?"]),
		new("sorath", "?", ["?"]),
		new("sprite", "?", ["?"]),
		new("sprite_debug", "Unused?", ["?"]),
		new("sprite_terrain", "?", ["?"]),
		new("squidarm", "?", ["?"]),
		new("squidarm_batch", "?", ["?"]),
		new("thorn", "?", ["?"]),
		new("tile", "?", ["?"]),
		new("tile2", "?", ["?"]),
		new("tile_batch", "?", ["?"]),
		new("unlit", "?", ["?"]),
		new("warp", "?", ["?"]),
		new("warp2", "?", ["?"]),
		new("warp2_batch", "?", ["?"]),
		new("warp_batch", "?", ["?"]),
		new("warp3", "?", ["?"]),
		new("warpeye", "?", ["?"]),
	];
}
