// ReSharper disable StringLiteralTypo
namespace DevilDaggersInfo.Web.Server.Utils.AssetInfo;

public static class DdTextures
{
	public static AssetInfoEntry[] All { get; } =
	[
		new("blood", "Blood decals", ["Particles"]),
		new("boid", "Skull I base", ["Enemy", "Skull I"]),
		new("boid2", "Skull II base", ["Enemy", "Skull II"]),
		new("boid2gib", "Skull II death", ["Death", "Enemy", "Skull II"]),
		new("boid2hit", "Skull II damage", ["Damage", "Enemy", "Skull II"]),
		new("boid2horns", "Skull II horns", ["Enemy", "Skull II"]),
		new("boid2hornsgib", "Skull II horns death", ["Death", "Enemy", "Skull II"]),
		new("boid2hornshit", "Skull II horns damage", ["Damage", "Enemy", "Skull II"]),
		new("boid2hornslev", "Transmuted Skull II horns", ["Enemy", "Transmuted Skull II"]),
		new("boid2lev", "Transmuted Skull II base", ["Enemy", "Transmuted Skull II"]),
		new("boid2levgib", "Transmuted Skull II death", ["Death", "Enemy", "Transmuted Skull II"]),
		new("boid3", "Skull III base", ["Enemy", "Skull III"]),
		new("boid3gib", "Skull III death", ["Death", "Enemy", "Skull III"]),
		new("boid3hit", "Skull III damage", ["Damage", "Enemy", "Skull III"]),
		new("boid3horns", "Skull III horns", ["Enemy", "Skull III"]),
		new("boid3hornsgib", "Skull III horns death", ["Death", "Enemy", "Skull III"]),
		new("boid3hornshit", "Skull III horns damage", ["Damage", "Enemy", "Skull III"]),
		new("boid3hornslev", "Transmuted Skull III horns", ["Enemy", "Transmuted Skull III"]),
		new("boid3jaw", "Skull III jaw", ["Enemy", "Skull III"]),
		new("boid3jawgib", "Skull III jaw death", ["Death", "Enemy", "Skull III"]),
		new("boid3jawhit", "Skull III jaw damage", ["Damage", "Enemy", "Skull III"]),
		new("boid3jawlev", "Transmuted Skull III jaw", ["Enemy", "Transmuted Skull III"]),
		new("boid3lev", "Transmuted Skull III base", ["Enemy", "Transmuted Skull III"]),
		new("boid4", "Skull IV base", ["Enemy", "Skull IV"]),
		new("boid4gib", "Skull IV death", ["Death", "Enemy", "Skull IV"]),
		new("boid4hit", "Skull IV damage", ["Damage", "Enemy", "Skull IV"]),
		new("boid4jaw", "Skull IV jaw", ["Enemy", "Skull IV"]),
		new("boid4jawgib", "Skull IV jaw death", ["Death", "Enemy", "Skull IV"]),
		new("boid4jawhit", "Skull IV jaw damage", ["Damage", "Enemy", "Skull IV"]),
		new("boid4jawlev", "Transmuted Skull IV jaw", ["Enemy", "Transmuted Skull IV"]),
		new("boid4lev", "Transmuted Skull IV base", ["Enemy", "Transmuted Skull IV"]),
		new("boidgib", "Skull I death", ["Death", "Enemy", "Skull I"]),
		new("boidhit", "Skull I damage", ["Damage", "Enemy", "Skull I"]),
		new("boidlev", "Transmuted Skull I", ["Enemy", "Transmuted Skull I"]),
		new("bottom", "Tile bottom?", ["Arena"]),
		new("crystal", "Unused", ["Unused"]),
		new("dagger", "Level 1 Dagger", ["Dagger"]),
		new("dagger0", "Pleb Lobby Dagger", ["Dagger", "Pleb"]),
		new("dagger2", "Level 2 Dagger", ["Dagger"]),
		new("dagger3", "Level 3 Dagger / Devil Lobby Dagger", ["Dagger", "Devil"]),
		new("dagger4", "Level 3 Homing Dagger", ["Dagger"]),
		new("dagger5", "Level 4 Dagger", ["Dagger"]),
		new("dagger6", "Level 4 Homing Dagger", ["Dagger"]),
		new("daggerbronze", "Bronze Lobby Dagger", ["Bronze", "Dagger"]),
		new("daggergold", "Golden Lobby Dagger", ["Dagger", "Golden"]),
		new("daggersilver", "Silver Lobby Dagger", ["Dagger", "Silver"]),
		new("emberflame", "Primary fire after-embers / Decals base", ["Particles"]),
		new("feather", "Unused", ["Unused"]),
		new("fontbronze", "Bronze font", ["Bronze", "Font", "UI"]),
		new("fontbronzeover", "Bronze font hover", ["Bronze", "Font", "Hover", "UI"]),
		new("fontdevil", "Devil font", ["Devil", "Font", "UI"]),
		new("fontdevilover", "Devil font hover", ["Devil", "Font", "Hover", "UI"]),
		new("fontgold", "Golden font", ["Font", "Golden", "UI"]),
		new("fontgoldover", "Golden font hover", ["Font", "Golden", "Hover", "UI"]),
		new("fontgrad", "Default UI font", ["Font", "UI"]),
		new("fontgrad2", "Default UI colored font", ["Font", "UI"]),
		new("fontgrad3", "Default UI colored font over", ["Font", "Hover", "UI"]),
		new("fontlevi", "Leviathan font", ["Font", "UI"]),
		new("fontlevibg", "Leviathan font mask", ["Font", "Hover", "UI"]),
		new("fontleviover", "Leviathan font over", ["Font", "Hover", "UI"]),
		new("fontpleb", "Pleb font", ["Font", "Pleb", "UI"]),
		new("fontplebover", "Pleb font hover", ["Font", "Hover", "Pleb", "UI"]),
		new("fontsilver", "Silver font", ["Font", "Silver", "UI"]),
		new("fontsilverover", "Silver font hover", ["Font", "Hover", "Silver", "UI"]),
		new("gib", "Gem (including gems in Squids)", ["Gem"]),
		new("gib1a", "Meat piece base", ["Gore"]),
		new("gib1b", "Meat piece base", ["Gore"]),
		new("gib1c", "Meat piece base", ["Gore"]),
		new("gib1d", "Meat piece base", ["Gore"]),
		new("gib2", "Alternate Gem (unused)", ["Gem"]),
		new("gib2a", "Meat piece base", ["Gore"]),
		new("gib2b", "Meat piece base", ["Gore"]),
		new("gib2c", "Meat piece base", ["Gore"]),
		new("gib2d", "Meat piece base", ["Gore"]),
		new("gib3a", "Meat piece base", ["Gore"]),
		new("gib3b", "Meat piece base", ["Gore"]),
		new("gib3c", "Meat piece base", ["Gore"]),
		new("gib3d", "Meat piece base", ["Gore"]),
		new("gigaegg", "Spider Egg II base", ["Enemy", "Spider Egg II"]),
		new("gigaspiderbody", "Spider II", ["Enemy", "Spider II"]),
		new("gigaspidercrest", "?", ["Enemy", "Spider II"]),
		new("gigaspidercrestgib", "Spider II death", ["Death", "Enemy", "Spider II"]),
		new("gigaspidercresthit", "Spider II damage", ["Damage", "Enemy", "Spider II"]),
		new("gigaspiderfangs", "Spider II Primary Fangs", ["Enemy", "Spider II"]),
		new("gigaspiderfangs2", "Spider II Secondary Fangs", ["Enemy", "Spider II"]),
		new("gigaspiderfangs2gib", "Spider II Fangs death", ["Death", "Enemy", "Spider II"]),
		new("gigaspiderfangs2hit", "Spider II Fangs damage", ["Damage", "Enemy", "Spider II"]),
		new("gigaspiderhead", "Spider II Gem Holder", ["Enemy", "Spider II"]),
		new("gigaspiderhorns", "Spider II Horns", ["Enemy", "Spider II"]),
		new("gigaspiderhornsgib", "Spider II Horns death", ["Death", "Enemy", "Spider II"]),
		new("gigaspiderhornshit", "Spider II Horns damage", ["Damage", "Enemy", "Spider II"]),
		new("gigaspiderjaw", "Spider II Mouth", ["Enemy", "Spider II"]),
		new("gigaspiderleg1", "Spider II Leg 1", ["Enemy", "Spider II"]),
		new("gigaspiderleg2", "Spider II Leg 2", ["Enemy", "Spider II"]),
		new("gigaspiderleg3", "Spider II Leg 3", ["Enemy", "Spider II"]),
		new("gigaspiderpalm", "Spider II Palm", ["Enemy", "Spider II"]),
		new("hand", "Level 1 Hand", ["Player"]),
		new("hand0", "Lobby Hand", ["Player"]),
		new("hand2", "Level 2 Hand", ["Player"]),
		new("hand3", "Level 3 Hand", ["Player"]),
		new("hand4", "Level 3 Hand Flash", ["Player"]),
		new("hand5", "Level 4 Hand", ["Player"]),
		new("hand6", "Level 4 Hand Flash", ["Player"]),
		new("iconcrosshair", "Accuracy Icon", ["Icon", "UI"]),
		new("icondagger", "Enemies Killed Icon", ["Icon", "UI"]),
		new("icondd", "Application Icon", ["Icon"]),
		new("iconeye", "Replay Recorded Run Icon", ["Icon", "UI"]),
		new("iconeye2", "Replay Recorded Run Icon hover", ["Hover", "Icon", "UI"]),
		new("icongem", "Gems Collected Icon", ["Icon", "UI"]),
		new("iconmaskcrosshair", "Accuracy Timeline Icon", ["Icon", "UI"]),
		new("iconmaskdagger", "Enemies Killed Timeline Icon", ["Icon", "UI"]),
		new("iconmaskgem", "Gems Collected Timeline Icon", ["Icon", "UI"]),
		new("iconmaskhoming", "Homing Daggers Timeline Icon", ["Icon", "UI"]),
		new("iconmaskskull", "Enemies Alive Timeline Icon", ["Icon", "UI"]),
		new("iconmaskstopwatch", "Scrubber Time Mark Icon", ["Icon", "UI"]),
		new("iconreplay", "Unused icon", ["Icon", "UI", "Unused"]),
		new("iconreplay2", "Unused icon", ["Icon", "UI", "Unused"]),
		new("iconskull", "Death Type / Total Deaths Icon", ["Icon", "UI"]),
		new("iconstopwatch", "Run Time Icon", ["Icon", "UI"]),
		new("levicrown", "?", ["Enemy", "Leviathan"]),
		new("levicrown2", "?", ["Enemy", "Leviathan"]),
		new("levicrown2jaw", "?", ["Enemy", "Leviathan"]),
		new("levicrownjaw", "?", ["Enemy", "Leviathan"]),
		new("levideath", "?", ["Death", "Enemy", "Leviathan"]),
		new("levidividerskull", "?", ["Enemy", "Leviathan"]),
		new("levileg1", "?", ["Enemy", "Leviathan"]),
		new("levileg2", "?", ["Enemy", "Leviathan"]),
		new("levileg3", "?", ["Enemy", "Leviathan"]),
		new("leviskull", "?", ["Enemy", "Leviathan"]),
		new("leviskull2", "?", ["Enemy", "Leviathan"]),
		new("leviskulljaw", "?", ["Enemy", "Leviathan"]),
		new("levitent", "?", ["Enemy", "Leviathan"]),
		new("levitent2", "?", ["Enemy", "Leviathan"]),
		new("levitentgib", "?", ["Death", "Enemy", "Leviathan"]),
		new("levitenthit", "?", ["Damage", "Enemy", "Leviathan"]),
		new("leviwarp", "Leviathan Secondary Dome effect", ["Enemy", "Leviathan"]),
		new("leviwarpover", "Leviathan Dome effect / Beckoned Skulls override", ["Enemy", "Leviathan"]),
		new("logodagger", "Splash Screen Dagger", ["UI"]),
		new("logodagger2", "Unused", ["UI"]),
		new("logohand", "Splash Screen Hand", ["UI"]),
		new("logotext", "Splash Screen Text", ["UI"]),
		new("lut", "Unused post filter", ["Post-processing", "Unused"]),
		new("minisquidarm", "Squid I Tentacle", ["Enemy", "Squid I"]),
		new("minisquidcrest", "Squid I Body", ["Enemy", "Squid I"]),
		new("minisquidcrestskull", "Squid I Gem Holder", ["Enemy", "Squid I"]),
		new("minisquidhorns", "Squid I Gem Holder Horns", ["Enemy", "Squid I"]),
		new("minisquidjaw", "Squid I Gem Holder Skull Jaw", ["Enemy", "Squid I"]),
		new("minisquidjawskull", "Squid I Gem Holder Skull", ["Enemy", "Squid I"]),
		new("pedeblackbody", "Gigapede Segment", ["Enemy", "Gigapede"]),
		new("pedeblackbodyfragged", "Gigapede Segment without Gem", ["Enemy", "Gigapede"]),
		new("pedeblackhead", "Gigapede Head", ["Enemy", "Gigapede"]),
		new("pedeblackjaw", "Gigapede Jaw", ["Enemy", "Gigapede"]),
		new("pedeblackleg1", "Gigapede Leg 1", ["Enemy", "Gigapede"]),
		new("pedeblackleg1fragged", "Gigapede Leg 1 without Gem", ["Enemy", "Gigapede"]),
		new("pedeblackleg2", "Gigapede Leg 2", ["Enemy", "Gigapede"]),
		new("pedeblackleg2fragged", "Gigapede Leg 2 without Gem", ["Enemy", "Gigapede"]),
		new("pedeblackleg3", "Gigapede Leg 3", ["Enemy", "Gigapede"]),
		new("pedeblackleg3fragged", "Gigapede Leg 3 without Gem", ["Enemy", "Gigapede"]),
		new("pedeblacktail", "Gigapede Tail", ["Enemy", "Gigapede"]),
		new("pedeblacktaillegs", "Gigapede Tail Legs", ["Enemy", "Gigapede"]),
		new("pedebody", "Centipede Body", ["Centipede", "Enemy"]),
		new("pedebodyfragged", "Centipede / Gigapede / Ghostpede Segment without gem", ["Centipede", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedebodygib", "Centipede / Gigapede / Ghostpede Segment death", ["Centipede", "Death", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedebodyhit", "Centipede / Gigapede / Ghostpede Segment damage", ["Centipede", "Damage", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedehead", "Centipede Head", ["Centipede", "Enemy"]),
		new("pedeheadgib", "Centipede / Gigapede / Ghostpede Head death", ["Centipede", "Death", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedeheadhit", "Centipede / Gigapede / Ghostpede Head damage", ["Centipede", "Damage", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedejaw", "Centipede Jaw", ["Centipede", "Enemy"]),
		new("pedejawgib", "Centipede / Gigapede / Ghostpede Jaw death", ["Centipede", "Death", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedejawhit", "Centipede / Gigapede / Ghostpede Jaw damage", ["Centipede", "Damage", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedeleg1", "Centipede Leg 1", ["Centipede", "Enemy"]),
		new("pedeleg1gib", "Centipede / Gigapede / Ghostpede Leg 1 death", ["Centipede", "Death", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedeleg1hit", "Centipede / Gigapede / Ghostpede Leg 1 damage", ["Centipede", "Damage", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedeleg2", "Centipede Leg 2", ["Centipede", "Enemy"]),
		new("pedeleg2gib", "Centipede / Gigapede / Ghostpede Leg 2 death", ["Centipede", "Death", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedeleg2hit", "Centipede / Gigapede / Ghostpede Leg 2 damage", ["Centipede", "Damage", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedeleg3", "Centipede Leg 3", ["Centipede", "Enemy"]),
		new("pedeleg3gib", "Centipede / Gigapede / Ghostpede Leg 3 death", ["Centipede", "Death", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedeleg3hit", "Centipede / Gigapede / Ghostpede Leg 3 damage", ["Centipede", "Damage", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedetail", "Centipede Tail", ["Centipede", "Enemy"]),
		new("pedetailgib", "Centipede / Gigapede / Ghostpede Tail death", ["Centipede", "Death", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedetailhit", "Centipede / Gigapede / Ghostpede Tail damage", ["Centipede", "Damage", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedetaillegs", "Centipede Tail Legs", ["Centipede", "Enemy"]),
		new("pedetaillegsgib", "Centipede / Gigapede / Ghostpede Tail Leg death", ["Centipede", "Death", "Enemy", "Ghostpede", "Gigapede"]),
		new("pedetaillegshit", "Centipede / Gigapede / Ghostpede Tail Leg damage", ["Centipede", "Damage", "Enemy", "Ghostpede", "Gigapede"]),
		new("pillar", "Tile sides", ["Arena"]),
		new("post_lut", "Arena In-game post filter", ["Post-processing"]),
		new("post_lut_bronzeflash", "Bronze Score post filter", ["Bronze", "Post-processing"]),
		new("post_lut_collect", "Gem Collected post filter", ["Post-processing"]),
		new("post_lut_dagger", "Lobby post filter", ["Post-processing"]),
		new("post_lut_death", "Post Death post filter", ["Post-processing"]),
		new("post_lut_devilflash", "Devil Score post filter", ["Devil", "Post-processing"]),
		new("post_lut_goldflash", "Golden Score post filter", ["Golden", "Post-processing"]),
		new("post_lut_leveldown", "Death fade out/flash post filter", ["Death", "Post-processing"]),
		new("post_lut_levelup", "Level Up post filter", ["Post-processing"]),
		new("post_lut_levi", "Leviathan Spawn post filter", ["Post-processing"]),
		new("post_lut_silverflash", "Silver Score post filter", ["Post-processing", "Silver"]),
		new("rubble", "Thorn Tile Destruction", ["Enemy", "Thorn"]),
		new("skulltile", "Unused", ["Unused"]),
		new("smokeblob", "Emerging Enemies", ["Particles"]),
		new("sorathmask", "Sorath Logo mask", ["Splash Screen"]),
		new("sorathstone", "Sorath Stone base", ["Easter Egg"]),
		new("sorathtexture", "Sorath Logo base", ["Splash Screen"]),
		new("sorathvector", "Sorath Logo filter", ["Splash Screen"]),
		new("spiderbody", "?", ["Enemy", "Spider I"]),
		new("spiderbodygib", "?", ["Enemy", "Spider I"]),
		new("spiderbodyhit", "?", ["Enemy", "Spider I"]),
		new("spideregg1", "Spider Egg I Goo base", ["Enemy", "Spider Egg I"]),
		new("spideregg2", "Spider Egg I base", ["Enemy", "Spider Egg I"]),
		new("spidereggflash", "Spider Egg I flashing", ["Enemy", "Spider Egg I"]),
		new("spiderfangs", "?", ["Enemy", "Spider I"]),
		new("spiderfangsgib", "?", ["Death", "Enemy", "Spider I"]),
		new("spiderfangshit", "?", ["Damage", "Enemy", "Spider I"]),
		new("spiderhead", "?", ["Enemy", "Spider I"]),
		new("spiderheadgib", "?", ["Death", "Enemy", "Spider I"]),
		new("spiderheadhit", "?", ["Damage", "Enemy", "Spider I"]),
		new("spiderjaw", "?", ["Enemy", "Spider I"]),
		new("spiderjawgib", "?", ["Death", "Enemy", "Spider I"]),
		new("spiderjawhit", "?", ["Damage", "Enemy", "Spider I"]),
		new("spiderleg1", "?", ["Enemy", "Spider I"]),
		new("spiderleg1gib", "?", ["Death", "Enemy", "Spider I"]),
		new("spiderleg1hit", "?", ["Damage", "Enemy", "Spider I"]),
		new("spiderleg2", "?", ["Enemy", "Spider I"]),
		new("spiderleg2gib", "?", ["Death", "Enemy", "Spider I"]),
		new("spiderleg2hit", "?", ["Damage", "Enemy", "Spider I"]),
		new("spiderleg3", "?", ["Enemy", "Spider I"]),
		new("spiderleg3gib", "?", ["Death", "Enemy", "Spider I"]),
		new("spiderleg3hit", "?", ["Damage", "Enemy", "Spider I"]),
		new("spiderling", "Spiderling Body base", ["Enemy", "Spiderling"]),
		new("spiderlinggib", "Spiderling Body death", ["Death", "Enemy", "Spiderling"]),
		new("spiderlinghit", "Spiderling Body damage", ["Damage", "Enemy", "Spiderling"]),
		new("spiderlingleg1", "Spiderling Leg 1", ["Enemy", "Spiderling"]),
		new("spiderlingleg1gib", "Spiderling Leg 1 death", ["Death", "Enemy", "Spiderling"]),
		new("spiderlingleg1hit", "Spiderling Leg 1", ["Enemy", "Spiderling"]),
		new("spiderlingleg2", "Spiderling Leg 2", ["Enemy", "Spiderling"]),
		new("spiderlingleg2gib", "Spiderling Leg 2 death", ["Death", "Enemy", "Spiderling"]),
		new("spiderlingleg2hit", "Spiderling Leg 2 damage", ["Damage", "Enemy", "Spiderling"]),
		new("spiderlingleg3", "Spiderling Leg 3", ["Enemy", "Spiderling"]),
		new("spiderlingleg3gib", "Spiderling Leg 3 death", ["Death", "Enemy", "Spiderling"]),
		new("spiderlingleg3hit", "Spiderling Leg 3 damage", ["Damage", "Enemy", "Spiderling"]),
		new("spiderlingpalm", "Spiderling Palm", ["Enemy", "Spiderling"]),
		new("spiderlingpalmgib", "Spiderling Palm death", ["Death", "Enemy", "Spiderling"]),
		new("spiderlingpalmhit", "Spiderling Palm damage", ["Damage", "Enemy", "Spiderling"]),
		new("spiderpalm", "Spider I Palm", ["Enemy", "Spider I"]),
		new("spiderpalmgib", "Spider I Palm death", ["Death", "Enemy", "Spider I"]),
		new("spiderpalmhit", "Spider I Palm damage", ["Damage", "Enemy", "Spider I"]),
		new("squidarm", "Squid II Tentacle", ["Enemy", "Squid II"]),
		new("squidarmgib", "Squid II Tentacle death", ["Death", "Enemy", "Squid II"]),
		new("squidarmhit", "Squid II Tentacle damage", ["Damage", "Enemy", "Squid II"]),
		new("squidcrest", "Squid II Body", ["Enemy", "Squid II"]),
		new("squidcrestgib", "Squid II Body damage", ["Damage", "Enemy", "Squid II"]),
		new("squidcresthit", "Squid II Body death", ["Death", "Enemy", "Squid II"]),
		new("squidcrestskull", "Squid II Gem Holder Skull", ["Enemy", "Squid II"]),
		new("squidcrestskullgib", "Squid II Gem Holder Skull death", ["Death", "Enemy", "Squid II"]),
		new("squidcrestskullhit", "Squid II Gem Holder Skull damage", ["Damage", "Enemy", "Squid II"]),
		new("squidhorns", "Squid II Horns", ["Enemy", "Squid II"]),
		new("squidjaws", "Squid II Gem Holder Skull Jaw", ["Enemy", "Squid II"]),
		new("squidjawsgib", "Squid II Gem Holder Skull Jaw death", ["Death", "Enemy", "Squid II"]),
		new("squidjawshit", "Squid II Gem Holder Skull Jaw damage", ["Damage", "Enemy", "Squid II"]),
		new("squidjawskull", "Squid II", ["Enemy", "Squid II"]),
		new("squidjawskullfragged", "Squid II Gem Holder Without Gem", ["Enemy", "Squid II"]),
		new("squidjawskullgib", "Squid II Gem Holder Skull Jaw", ["Enemy", "Squid II"]),
		new("squidjawskullhit", "Squid II Gem Holder Skull Jaw death", ["Death", "Enemy", "Squid II"]),
		new("squidteeth", "Squid II Bottom Teeth", ["Enemy", "Squid II"]),
		new("squidteethgib", "Squid II Bottom Teeth death", ["Death", "Enemy", "Squid II"]),
		new("squidteethhit", "Squid II Bottom Teeth damage", ["Damage", "Enemy", "Squid II"]),
		new("statue1", "Player Number 3", ["Easter Egg"]),
		new("statue2", "Player Number 2", ["Easter Egg"]),
		new("statue3", "Player Number 1", ["Easter Egg"]),
		new("thorn", "Thorn Body base", ["Enemy", "Thorn"]),
		new("thorngib", "Thorn Body death", ["Death", "Enemy", "Thorn"]),
		new("thornhit", "Thorn Body damage", ["Damage", "Enemy", "Thorn"]),
		new("tile", "Floor", ["Arena"]),
		new("ultrapedebody", "Ghostpede segment", ["Enemy", "Ghostpede"]),
		new("ultrapedebodyfragged", "Ghostpede segment without gem", ["Enemy", "Ghostpede"]),
		new("ultrapedecrown", "Ghostpede extra horns", ["Enemy", "Ghostpede"]),
		new("ultrapedecrowngib", "Ghostpede extra horns death", ["Death", "Enemy", "Ghostpede"]),
		new("ultrapedecrownhit", "Ghostpede extra horns damage", ["Damage", "Enemy", "Ghostpede"]),
		new("ultrapedehead", "Ghostpede head", ["Enemy", "Ghostpede"]),
		new("ultrapedejaw", "Ghostpede jaw", ["Enemy", "Ghostpede"]),
		new("ultrapedeleg1", "Ghostpede leg", ["Enemy", "Ghostpede"]),
		new("ultrapedeleg2", "Ghostpede leg", ["Enemy", "Ghostpede"]),
		new("ultrapedeleg3", "Ghostpede leg", ["Enemy", "Ghostpede"]),
		new("ultrapedetail", "Ghostpede tail", ["Enemy", "Ghostpede"]),
		new("ultrasquidcrest", "Squid III body", ["Enemy", "Squid III"]),
		new("ultrasquidcrestskull", "Squid III body skull", ["Enemy", "Squid III"]),
		new("ultrasquidhorns", "Squid III skull gem holder horns", ["Enemy", "Squid III"]),
		new("ultrasquidjaw", "Squid III skull jaw gem holder", ["Enemy", "Squid III"]),
		new("ultrasquidjawskull", "Squid III skull gem holder", ["Enemy", "Squid III"]),
	];
}
