<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="MockQueryable.NSubstitute" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <!-- TODO: Reference DevilDaggersInfo.Web.Server.Domain or rename the test project. -->
    <ProjectReference Include="..\..\DevilDaggersInfo.Web.Server\DevilDaggersInfo.Web.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\**\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <GlobalAnalyzerConfigFiles Include="..\Tests.globalconfig" />
  </ItemGroup>

</Project>
