namespace DevilDaggersInfo.Core.Asset;

public static class DdObjectBindings
{
	public static readonly IReadOnlyList<ObjectBindingAssetInfo> All = new List<ObjectBindingAssetInfo>
	{
		new("bat", false),
		new("boid", false),
		new("boid_pop", false),
		new("dagger", false),
		new("dagger1", false),
		new("dagger2", false),
		new("dagger3", false),
		new("dagger4", false),
		new("dagger5", false),
		new("dagger6", false),
		new("daggerbronze", false),
		new("daggerdevil", false),
		new("daggergold", false),
		new("daggerlevi", false),
		new("daggersilver", false),
		new("gib", false),
		new("gibegg", false),
		new("gigaegg", false),
		new("hand", false),
		new("hand0", false),
		new("hand2", false),
		new("hand3", false),
		new("hand4", false),
		new("hand5", false),
		new("hand6", false),
		new("immortaleye", false),
		new("immortaleyehit", false),
		new("levitent", false),
		new("levitentgib", false),
		new("levitenthit", false),
		new("leviwarp", false),
		new("leviwarp2", false),
		new("leviwarp3", false),
		new("logodagger", false),
		new("logohand", false),
		new("logotext", false),
		new("minisquidarm", false),
		new("particle", false),
		new("particle2", false),
		new("particle_decal", false),
		new("pedebody", false),
		new("pedehead", false),
		new("pedejaw", false),
		new("pedeleg1", false),
		new("pedeleg2", false),
		new("pedeleg3", false),
		new("pedetail", false),
		new("skullscroll", false),
		new("skullwarp", false),
		new("sorathlogo", false),
		new("spideregg1", false),
		new("spideregg2", false),
		new("spidereggflash", false),
		new("squidarm", false),
		new("squidarmgib", false),
		new("squidarmhit", false),
		new("squidteeth", false),
		new("squidteethgib", false),
		new("squidteethhit", false),
		new("thorn", false),
		new("thornhit", false),
		new("tile", false),
		new("tile2", false),
	};
}
