<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="Current">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AnalysisMode>All</AnalysisMode>
		<RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
		<ImplicitUsings>true</ImplicitUsings>
		<InvariantGlobalization>true</InvariantGlobalization>
		<WarningsAsErrors>nullable</WarningsAsErrors>
		<LangVersion>14.0</LangVersion>
	</PropertyGroup>

	<PropertyGroup Label="Custom properties">
		<TailwindBuild>true</TailwindBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugType>None</DebugType>
		<DebugSymbols>False</DebugSymbols>
	</PropertyGroup>

</Project>
