on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.200' # TODO: Use 7.0.201 when https://github.com/actions/setup-dotnet/issues/388 is fixed.
        include-prerelease: false
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build src/DevilDaggersInfo.sln -c Release
    - name: Test
      run: dotnet test src/DevilDaggersInfo.sln -c Release --no-build
