on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.200'
          include-prerelease: false
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build src/DevilDaggersInfo.Web.slnx -c Release
      - name: Test
        run: dotnet test src/DevilDaggersInfo.Web.slnx -c Release --no-build
