on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Set up dotnet
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
      - name: Checkout
        uses: actions/checkout@v7
      - name: Build
        run: dotnet build src/DevilDaggersInfo.Web.slnx -c Release
      - name: Test
        run: dotnet test --solution src/DevilDaggersInfo.Web.slnx -c Release --no-build
      - name: Pack
        run: |
          dotnet pack src/DevilDaggersInfo.Web.ApiSpec.Admin -c Release -o .
          dotnet pack src/DevilDaggersInfo.Web.ApiSpec.Main -c Release -o .
          dotnet pack src/DevilDaggersInfo.Web.ApiSpec.Tools -c Release -o .
      - name: Push
        run: dotnet nuget push *.nupkg -s nuget.org -k ${NUGET_SECRET} -n --skip-duplicate
        env:
          NUGET_SECRET: ${{ secrets.NUGET_SECRET }}
